export const PAYMENT_ERROR_CODES = [
  'SESSION_EXPIRED',
  'SESSION_RESUME_REQUIRED',
  'SOLD_OUT',
  'ORDER_NOT_OPEN',
  'RESERVATION_EXPIRED',
  'EVENT_UNAVAILABLE',
  'LISTING_UNAVAILABLE',
  'INVALID_STATE',
  'PRICE_MISMATCH',
  'RATE_LIMITED',
  'ORGANIZER_STRIPE_NOT_CONNECTED',
  'ORGANIZER_STRIPE_CHARGES_DISABLED',
  'ORGANIZER_STRIPE_ONBOARDING_INCOMPLETE',
  'ORDER_CONNECTED_ACCOUNT_MISMATCH',
  'TERMS_NOT_ACCEPTED',
] as const;

export type PaymentErrorCode = (typeof PAYMENT_ERROR_CODES)[number];

const PAYMENT_ERROR_CODE_SET = new Set<string>(PAYMENT_ERROR_CODES);

export function isPaymentErrorCode(code: string): code is PaymentErrorCode {
  return PAYMENT_ERROR_CODE_SET.has(code);
}
