import fs from 'node:fs';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';

import {HELP_CENTER_ENABLED} from '../src/app/features/help/help-center.config';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const frontendRoot = path.resolve(scriptDir, '..');
const publicDir = path.join(frontendRoot, 'public');
const generatedPublicDir = path.join(frontendRoot, '.generated-public');
const generatedRoutesFile = path.join(
  frontendRoot,
  'src',
  'app',
  'features',
  'help',
  'help-center.routes.generated.ts',
);
const generatedFooterLinkFile = path.join(
  frontendRoot,
  'src',
  'app',
  'features',
  'help',
  'help-center.footer-link.generated.ts',
);
const generatedAuditRoutesFile = path.join(
  frontendRoot,
  'e2e',
  'audit',
  'help-center-audit-routes.generated.ts',
);
const docsManifestScript = path.join(
  frontendRoot,
  '..',
  'scripts',
  'build-docs-manifest.ts',
);

const disabledRoutesSource = `import type {Routes} from '@angular/router';

// Generated by frontend/scripts/sync-help-center-shipping.ts.
export const HELP_CENTER_ROUTES: Routes = [];
`;

const enabledRoutesSource = `import type {Routes} from '@angular/router';

// Generated by frontend/scripts/sync-help-center-shipping.ts.
export const HELP_CENTER_ROUTES: Routes = [
  {
    path: 'help',
    loadChildren: () => import('./help.routes').then((m) => m.HELP_ROUTES),
  },
];
`;

const disabledFooterLinkSource = `// Generated by frontend/scripts/sync-help-center-shipping.ts.
export const HELP_CENTER_FOOTER_LINKS: {
  label: string;
  routerLink: string;
}[] = [];
`;

const enabledFooterLinkSource = `// Generated by frontend/scripts/sync-help-center-shipping.ts.
export const HELP_CENTER_FOOTER_LINKS: {
  label: string;
  routerLink: string;
}[] = [
  {
    label: 'Help',
    routerLink: '/help',
  },
];
`;

const disabledAuditRoutesSource = `import type {AuditRoute} from './audit-types';

// Generated by frontend/scripts/sync-help-center-shipping.ts.
export const HELP_CENTER_AUDIT_ROUTES: AuditRoute[] = [];
`;

const enabledAuditRoutesSource = `import type {AuditRoute} from './audit-types';

// Generated by frontend/scripts/sync-help-center-shipping.ts.
export const HELP_CENTER_AUDIT_ROUTES: AuditRoute[] = [
  {
    label: 'Help',
    path: '/help',
    role: 'anon',
    readyLocator: 'role=heading[level=1]',
  },
];
`;

function shouldCopyPublicAsset(src: string): boolean {
  if (HELP_CENTER_ENABLED) return true;

  const relativePath = path.relative(publicDir, src);
  const [firstSegment] = relativePath.split(path.sep);
  return firstSegment !== 'docs';
}

function writeIfChanged(filePath: string, content: string): void {
  if (
    fs.existsSync(filePath) &&
    fs.readFileSync(filePath, 'utf-8') === content
  ) {
    return;
  }

  fs.writeFileSync(filePath, content);
}

export function syncHelpCenterRoutes(): void {
  writeIfChanged(
    generatedRoutesFile,
    HELP_CENTER_ENABLED ? enabledRoutesSource : disabledRoutesSource,
  );
  writeIfChanged(
    generatedFooterLinkFile,
    HELP_CENTER_ENABLED ? enabledFooterLinkSource : disabledFooterLinkSource,
  );
  writeIfChanged(
    generatedAuditRoutesFile,
    HELP_CENTER_ENABLED ? enabledAuditRoutesSource : disabledAuditRoutesSource,
  );
}

export function syncDocsManifestWhenEnabled(): void {
  if (!HELP_CENTER_ENABLED) return;

  execFileSync('tsx', [docsManifestScript], {
    cwd: frontendRoot,
    env: process.env,
    stdio: 'inherit',
  });
}

export function preparePublicAssets(): void {
  fs.rmSync(generatedPublicDir, {recursive: true, force: true});
  fs.mkdirSync(generatedPublicDir, {recursive: true});
  fs.cpSync(publicDir, generatedPublicDir, {
    recursive: true,
    dereference: true,
    filter: shouldCopyPublicAsset,
  });
}

export function syncHelpCenterShipping(): void {
  syncHelpCenterRoutes();
  syncDocsManifestWhenEnabled();
  preparePublicAssets();
}
