/**
 * Codemod: rewrite callers of `api.testing_functions.*` and
 * `internal.testing_functions.*` to per-domain paths under
 * `api.testing.<domain>.*` / `internal.testing.<domain>.*`.
 *
 * Background:
 *   `backend/convex/testing_functions.ts` is being split into
 *   `backend/convex/testing/<domain>.ts` files. Function names are
 *   preserved; only the module path changes. See
 *   `testing-functions-map.ts` for the canonical name→domain table.
 *
 * CLI:
 *   pnpm tsx backend/scripts/codemods/testing-functions-migration.ts [flags]
 *
 * Flags:
 *   --dry-run        (default) print diffs and a summary; write nothing
 *   --write          actually write rewrites to disk
 *   --verbose        per-file diagnostics
 *   --paths <glob>   limit scope (repeatable); default scans backend/, frontend/, scripts/
 *   --allow-unknowns exit 0 even if unknown names or dynamic accesses are reported
 *
 * The script does NOT touch:
 *   - backend/convex/testing_functions.ts (the source file; deleted in a later step)
 *   - backend/convex/_generated/api.d.ts and siblings (regenerated by Convex)
 *   - any path under node_modules/, _generated/, dist/, build/, .convex-local/
 */

import {existsSync, readFileSync, writeFileSync} from 'node:fs';
import {dirname, relative, resolve} from 'node:path';
import {fileURLToPath, pathToFileURL} from 'node:url';

import {Project, SyntaxKind, type Node, type SourceFile} from 'ts-morph';

import {
  TESTING_FUNCTIONS_DOMAIN_MAP,
  isKnownTestingFunction,
  type KnownTestingFunctionName,
  type TestingFunctionDomain,
} from './testing-functions-map.ts';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const BACKEND_ROOT = resolve(SCRIPT_DIR, '..', '..');
const REPO_ROOT = resolve(BACKEND_ROOT, '..');

const DEFAULT_SCAN_GLOBS = [
  'backend/**/*.{ts,tsx}',
  'frontend/**/*.{ts,tsx}',
  'scripts/**/*.{ts,tsx}',
];

const EXCLUDE_GLOBS = [
  '**/node_modules/**',
  '**/_generated/**',
  '**/dist/**',
  '**/build/**',
  '**/.convex-local/**',
  '**/.angular/**',
  '**/.next/**',
  '**/coverage/**',
];

/** Files we explicitly refuse to rewrite, even if matched by a glob. */
const EXPLICITLY_PROTECTED = new Set<string>([
  resolve(BACKEND_ROOT, 'convex/testing_functions.ts'),
]);

export type Occurrence = {
  /** Root identifier — 'api' or 'internal'. */
  root: 'api' | 'internal';
  /** Leaf function name after testing_functions. */
  name: string;
  /** Domain resolved from the map; null if unknown. */
  domain: TestingFunctionDomain | null;
  /** 1-based line number of the `testing_functions` token. */
  line: number;
  /** 1-based column of the `testing_functions` token. */
  column: number;
};

export type UnknownOccurrence = Occurrence & {domain: null; name: string};

export type DynamicOccurrence = {
  root: 'api' | 'internal';
  line: number;
  column: number;
  /** Short description of what the dynamic access looks like, for reports. */
  description: string;
};

export type FileReport = {
  filePath: string;
  before: string;
  after: string;
  rewrites: number;
  unknowns: UnknownOccurrence[];
  dynamic: DynamicOccurrence[];
};

export type RunSummary = {
  filesScanned: number;
  filesTouched: number;
  occurrencesRewritten: number;
  unknowns: Array<UnknownOccurrence & {filePath: string}>;
  dynamic: Array<DynamicOccurrence & {filePath: string}>;
};

export type RewriteOptions = {
  /** When true, suppress tsmorph-specific optimizations. Core transform
   *  does not depend on this, but callers may want it to seed fixtures. */
  sourceText: string;
  /** Virtual path used for ts-morph source file registration. Does not
   *  need to exist on disk. */
  virtualPath?: string;
};

/**
 * Core pure transform: given source text, returns the rewritten text plus
 * a per-file report. Does not touch disk. Safe to call from tests.
 */
export function rewriteSourceText(
  options: RewriteOptions,
): Omit<FileReport, 'filePath'> {
  const {sourceText, virtualPath = '/virtual/source.ts'} = options;
  const project = new Project({
    useInMemoryFileSystem: true,
    compilerOptions: {allowJs: true, jsx: 2 /* Preserve */},
  });
  const source = project.createSourceFile(virtualPath, sourceText);

  return transformSourceFile(source, sourceText);
}

function transformSourceFile(
  source: SourceFile,
  before: string,
): Omit<FileReport, 'filePath'> {
  const unknowns: UnknownOccurrence[] = [];
  const dynamic: DynamicOccurrence[] = [];
  let rewrites = 0;

  /*
   * We process in two passes.
   *
   * Pass 1: handle property accesses `api.testing_functions.<Name>` and
   *         `internal.testing_functions.<Name>` where the segment following
   *         `testing_functions` is a plain identifier. We rewrite in place
   *         to `api.testing.<domain>.<Name>` (or `internal.testing....`).
   *
   * Pass 2: handle remaining uses of the two-hop form
   *         `api.testing_functions` / `internal.testing_functions` that
   *         are NOT immediately followed by a known property access.
   *         This covers destructuring (`const {x} = api.testing_functions`),
   *         element access (`api.testing_functions[expr]`), and any other
   *         dangling reference. We report these, and only rewrite the
   *         destructuring case — where we can recover the name(s).
   *
   * Two passes keeps the AST stable: ts-morph's in-place rewrites invalidate
   * descendant nodes within the same traversal, so we collect edits, sort
   * descending by position, and apply them from the end of the file.
   */

  type Edit = {
    startLine: number;
    startCol: number;
    pos: number;
    end: number;
    replacement: string;
  };
  const edits: Edit[] = [];

  // Pass 1: property-access rewrites
  for (const propAccess of source.getDescendantsOfKind(
    SyntaxKind.PropertyAccessExpression,
  )) {
    // We want the outer `api.testing_functions.Name` form, so match where
    // `propAccess.expression` is itself a PropertyAccessExpression whose
    // tail is `testing_functions` and whose base is `api`/`internal`.
    const expr = propAccess.getExpression();
    if (!expr.isKind(SyntaxKind.PropertyAccessExpression)) continue;

    const tailName = expr.getName();
    if (tailName !== 'testing_functions') continue;

    const baseExpr = expr.getExpression();
    if (!baseExpr.isKind(SyntaxKind.Identifier)) continue;

    const rootText = baseExpr.getText();
    if (rootText !== 'api' && rootText !== 'internal') continue;

    const leafName = propAccess.getName();
    const {line, column} = source.getLineAndColumnAtPos(expr.getNameNode().getStart());

    if (!isKnownTestingFunction(leafName)) {
      unknowns.push({
        root: rootText,
        name: leafName,
        domain: null,
        line,
        column,
      });
      continue;
    }

    const domain = TESTING_FUNCTIONS_DOMAIN_MAP[leafName as KnownTestingFunctionName];
    const replacement = `${rootText}.testing.${domain}.${leafName}`;
    edits.push({
      startLine: line,
      startCol: column,
      pos: propAccess.getStart(),
      end: propAccess.getEnd(),
      replacement,
    });
    rewrites += 1;
  }

  // Pass 2: handle `api.testing_functions` / `internal.testing_functions`
  // forms that are NOT already part of a handled three-hop property chain.
  for (const propAccess of source.getDescendantsOfKind(
    SyntaxKind.PropertyAccessExpression,
  )) {
    if (propAccess.getName() !== 'testing_functions') continue;
    const base = propAccess.getExpression();
    if (!base.isKind(SyntaxKind.Identifier)) continue;
    const rootText = base.getText();
    if (rootText !== 'api' && rootText !== 'internal') continue;

    // Skip nodes whose parent is another property access with the same
    // base — those were handled in pass 1 (or reported as unknown above).
    const parent = propAccess.getParent();
    if (parent && parent.isKind(SyntaxKind.PropertyAccessExpression)) {
      const parentBase = parent.getExpression();
      if (parentBase === propAccess) {
        continue;
      }
    }

    // Destructuring: `const { seedEvent } = api.testing_functions`
    const varDecl = findAncestorVariableDeclaration(propAccess);
    if (
      parent &&
      parent.isKind(SyntaxKind.VariableDeclaration) &&
      varDecl !== undefined
    ) {
      const nameNode = varDecl.getNameNode();
      if (nameNode.isKind(SyntaxKind.ObjectBindingPattern)) {
        // We cannot rewrite a single `api.testing_functions` base to a
        // single per-domain path when the destructuring references
        // functions from multiple domains. In that case we report and
        // skip. Otherwise, rewrite to `api.testing.<domain>`.
        const destructured: string[] = [];
        for (const element of nameNode.getElements()) {
          const prop = element.getPropertyNameNode() ?? element.getNameNode();
          if (prop.isKind(SyntaxKind.Identifier)) {
            destructured.push(prop.getText());
          }
        }

        const domains = new Set<string>();
        const unknownDestructured: string[] = [];
        for (const name of destructured) {
          if (isKnownTestingFunction(name)) {
            domains.add(
              TESTING_FUNCTIONS_DOMAIN_MAP[name as KnownTestingFunctionName],
            );
          } else {
            unknownDestructured.push(name);
          }
        }

        const {line, column} = source.getLineAndColumnAtPos(
          propAccess.getNameNode().getStart(),
        );

        for (const unknownName of unknownDestructured) {
          unknowns.push({
            root: rootText,
            name: unknownName,
            domain: null,
            line,
            column,
          });
        }

        if (domains.size === 1) {
          const [domain] = [...domains];
          edits.push({
            startLine: line,
            startCol: column,
            pos: propAccess.getStart(),
            end: propAccess.getEnd(),
            replacement: `${rootText}.testing.${domain}`,
          });
          rewrites += 1;
        } else if (domains.size > 1) {
          // Mixed-domain destructuring is effectively dynamic — we cannot
          // pick a single replacement path. Report and leave unchanged.
          dynamic.push({
            root: rootText,
            line,
            column,
            description: `mixed-domain destructuring from ${rootText}.testing_functions: ${[
              ...domains,
            ]
              .sort()
              .join(', ')}`,
          });
        }
        continue;
      }
    }

    // Element access: `api.testing_functions[someVar]` or computed.
    if (parent && parent.isKind(SyntaxKind.ElementAccessExpression)) {
      const {line, column} = source.getLineAndColumnAtPos(
        propAccess.getNameNode().getStart(),
      );
      dynamic.push({
        root: rootText,
        line,
        column,
        description: `dynamic property access ${rootText}.testing_functions[...]`,
      });
      continue;
    }

    // Any other lingering reference. Report for manual review.
    const {line, column} = source.getLineAndColumnAtPos(
      propAccess.getNameNode().getStart(),
    );
    dynamic.push({
      root: rootText,
      line,
      column,
      description: `unhandled reference to ${rootText}.testing_functions`,
    });
  }

  // Apply edits from end to start so positions remain valid.
  edits.sort((a, b) => b.pos - a.pos);
  let after = before;
  for (const edit of edits) {
    after = after.slice(0, edit.pos) + edit.replacement + after.slice(edit.end);
  }

  return {before, after, rewrites, unknowns, dynamic};
}

function findAncestorVariableDeclaration(node: Node) {
  let current: Node | undefined = node.getParent();
  while (current) {
    if (current.isKind(SyntaxKind.VariableDeclaration)) {
      return current;
    }
    // Stop ascending once we leave an initializer-ish context.
    if (
      current.isKind(SyntaxKind.Block) ||
      current.isKind(SyntaxKind.SourceFile)
    ) {
      return undefined;
    }
    current = current.getParent();
  }
  return undefined;
}

/**
 * Filesystem runner. Collects matching files, applies `rewriteSourceText`,
 * and (when write is true) persists changes.
 */
export type RunOptions = {
  repoRoot?: string;
  paths?: string[];
  dryRun: boolean;
  verbose: boolean;
  allowUnknowns: boolean;
  /** Hook for tests to inject a virtual filesystem. */
  readFile?: (absolutePath: string) => string;
  writeFile?: (absolutePath: string, contents: string) => void;
  /** Hook for tests to inject the list of candidate files. */
  listFiles?: (globs: string[]) => string[];
  /** Hook for tests to inject a virtual filesystem existence check. */
  exists?: (absolutePath: string) => boolean;
  /** Output sink. Defaults to process.stdout. */
  log?: (message: string) => void;
};

export function run(options: RunOptions): {summary: RunSummary; exitCode: number} {
  const repoRoot = options.repoRoot ?? REPO_ROOT;
  const readFile = options.readFile ?? ((p) => readFileSync(p, 'utf8'));
  const writeFile =
    options.writeFile ?? ((p, c) => writeFileSync(p, c, 'utf8'));
  const log = options.log ?? ((m) => process.stdout.write(`${m}\n`));
  const listFiles =
    options.listFiles ??
    ((globs) => defaultListFiles(repoRoot, globs, EXCLUDE_GLOBS));
  const exists = options.exists ?? existsSync;

  const scanGlobs = options.paths && options.paths.length > 0
    ? options.paths
    : DEFAULT_SCAN_GLOBS;

  const candidateFiles = listFiles(scanGlobs);

  const summary: RunSummary = {
    filesScanned: 0,
    filesTouched: 0,
    occurrencesRewritten: 0,
    unknowns: [],
    dynamic: [],
  };

  for (const absolutePath of candidateFiles) {
    if (EXPLICITLY_PROTECTED.has(absolutePath)) continue;
    if (!exists(absolutePath)) continue;

    summary.filesScanned += 1;
    const sourceText = readFile(absolutePath);

    // Fast path: skip files that do not mention `testing_functions`.
    if (!sourceText.includes('testing_functions')) continue;

    const report = rewriteSourceText({
      sourceText,
      virtualPath: absolutePath,
    });
    const fileReport: FileReport = {
      filePath: absolutePath,
      ...report,
    };

    for (const u of fileReport.unknowns) {
      summary.unknowns.push({...u, filePath: absolutePath});
    }
    for (const d of fileReport.dynamic) {
      summary.dynamic.push({...d, filePath: absolutePath});
    }

    if (fileReport.rewrites === 0) {
      if (options.verbose) {
        const rel = relative(repoRoot, absolutePath);
        log(`no-op: ${rel}`);
      }
      continue;
    }

    summary.filesTouched += 1;
    summary.occurrencesRewritten += fileReport.rewrites;

    const rel = relative(repoRoot, absolutePath);
    if (options.dryRun) {
      log(`--- ${rel} (${fileReport.rewrites} rewrite(s))`);
      log(renderDiff(fileReport.before, fileReport.after));
    } else {
      writeFile(absolutePath, fileReport.after);
      log(`rewrote: ${rel} (${fileReport.rewrites} occurrence(s))`);
    }
  }

  log('');
  log('Summary:');
  log(`  files scanned:          ${summary.filesScanned}`);
  log(`  files touched:          ${summary.filesTouched}`);
  log(`  occurrences rewritten:  ${summary.occurrencesRewritten}`);
  log(`  unknowns:               ${summary.unknowns.length}`);
  log(`  dynamic accesses:       ${summary.dynamic.length}`);

  if (summary.unknowns.length > 0) {
    log('');
    log('Unknown names (manual review required):');
    for (const u of summary.unknowns) {
      const rel = relative(repoRoot, u.filePath);
      log(`  ${rel}:${u.line}:${u.column} ${u.root}.testing_functions.${u.name}`);
    }
  }

  if (summary.dynamic.length > 0) {
    log('');
    log('Dynamic / destructuring accesses (manual review required):');
    for (const d of summary.dynamic) {
      const rel = relative(repoRoot, d.filePath);
      log(`  ${rel}:${d.line}:${d.column} ${d.description}`);
    }
  }

  const hasIssues = summary.unknowns.length + summary.dynamic.length > 0;
  const exitCode = hasIssues && !options.allowUnknowns ? 1 : 0;

  return {summary, exitCode};
}

function renderDiff(before: string, after: string): string {
  // A line-by-line unified-ish diff. Not a true patch format; enough to
  // eyeball in --dry-run output. Users who want a real patch can run the
  // write and inspect `git diff`.
  const beforeLines = before.split('\n');
  const afterLines = after.split('\n');
  const out: string[] = [];
  const max = Math.max(beforeLines.length, afterLines.length);
  for (let i = 0; i < max; i += 1) {
    const a = beforeLines[i];
    const b = afterLines[i];
    if (a === b) continue;
    if (a !== undefined) out.push(`- ${a}`);
    if (b !== undefined) out.push(`+ ${b}`);
  }
  return out.join('\n');
}

function defaultListFiles(
  repoRoot: string,
  scanGlobs: readonly string[],
  excludeGlobs: readonly string[],
): string[] {
  // We use ts-morph's built-in glob via a throwaway Project so we stay
  // consistent with how ts-morph resolves paths elsewhere.
  const project = new Project({
    skipAddingFilesFromTsConfig: true,
    compilerOptions: {allowJs: true},
  });
  project.addSourceFilesAtPaths(
    scanGlobs.map((g) => (g.startsWith('/') ? g : `${repoRoot}/${g}`)),
  );
  const resolvedExcludes = excludeGlobs.map((g) =>
    g.startsWith('/') ? g : `${repoRoot}/${g}`,
  );
  const excludePatterns = resolvedExcludes.map((g) => globToRegExp(g));

  const files = project
    .getSourceFiles()
    .map((s) => s.getFilePath())
    .filter((p) => !excludePatterns.some((rx) => rx.test(p)));
  return [...new Set(files)].sort();
}

function globToRegExp(glob: string): RegExp {
  // Minimal glob: ** → .*, * → [^/]*, everything else literal. Good enough
  // for our exclusion patterns.
  const escaped = glob
    .replace(/[.+^${}()|[\]\\]/g, '\\$&')
    .replace(/\*\*/g, '__GLOBSTAR__')
    .replace(/\*/g, '[^/]*')
    .replace(/__GLOBSTAR__/g, '.*');
  return new RegExp(`^${escaped}$`);
}

/* ------------------------------- CLI entry ------------------------------- */

export type ParsedArgs = {
  dryRun: boolean;
  write: boolean;
  verbose: boolean;
  allowUnknowns: boolean;
  paths: string[];
};

export function parseArgs(argv: readonly string[]): ParsedArgs {
  let dryRun = true;
  let write = false;
  let verbose = false;
  let allowUnknowns = false;
  const paths: string[] = [];

  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    switch (arg) {
      case '--dry-run':
        dryRun = true;
        write = false;
        break;
      case '--write':
        write = true;
        dryRun = false;
        break;
      case '--verbose':
        verbose = true;
        break;
      case '--allow-unknowns':
        allowUnknowns = true;
        break;
      case '--paths': {
        const value = argv[i + 1];
        if (value === undefined) {
          throw new Error('--paths requires a value');
        }
        paths.push(value);
        i += 1;
        break;
      }
      default:
        if (arg === undefined) continue;
        if (arg.startsWith('--paths=')) {
          paths.push(arg.slice('--paths='.length));
          break;
        }
        throw new Error(`Unknown argument: ${arg}`);
    }
  }

  return {dryRun, write, verbose, allowUnknowns, paths};
}

function main(): void {
  const parsed = parseArgs(process.argv.slice(2));
  const {exitCode} = run({
    dryRun: parsed.dryRun,
    verbose: parsed.verbose,
    allowUnknowns: parsed.allowUnknowns,
    paths: parsed.paths.length > 0 ? parsed.paths : undefined,
  });
  if (exitCode !== 0) process.exitCode = exitCode;
}

if (process.argv[1] !== undefined) {
  const entryUrl = pathToFileURL(process.argv[1]).href;
  if (import.meta.url === entryUrl) {
    main();
  }
}
